:allow-uri-read:
:stylesheet: https://tech.swissmicros.com/User-Manuals/usermanuals.css
:linkcss:
:lang: en
:toc: left
:toclevels: 3
:doctype: book
:icons: font

[[firmware_update]]
== Firmware Update

WARNING: Please remember it is always wise to make FAT disk backups periodically and especially before any update.

TIP: The latest firmware version is available at https://technical.swissmicros.com/{webdir}/firmware/


*If you are looking for quick update instructions you most probably want to follow <<quick_update_guide,Quick Update Guide>>.*


ifdef::add-QSPI[]
{platform} has two firmware areas. First one is the main flash area which is updated with each firmware update, the second one is auxiliary QSPI area which is rarely updated and special update menu appears when the firmware needs new QSPI contents.

WARNING: No action related to QSPI contents is needed until firmware requests QSPI update by showing <<dmcp_sys_menu,DMCP System menu>>
(or <<qspi_load_menu,"QSPI Load" menu>> for firmware versions before 3.7).
endif::[]

ifdef::add-OLDFW[]
Note that since version 3.7 the calculator operating system (called DMCP) is separated from the {platform} program. Thus, both DMCP and {platform} program could be loaded separately. For more details see <<changes_since_3.7, Changes since v3.7>> and
<<quick_update_guide,Quick DMCP and PGM Update Guide>> for separate DMCP and PGM update procedure.
endif::[]

The preferred firmware update method is by copying firmware file to
<<internal_fat_disk, calculator FAT disk>>.
ifdef::add-OLDFW[]
This update method is available since DMCP version 3.5.
endif::[]
See <<quick_update_guide,Quick Update Guide>> for update procedure.


Firmware update from FAT disk is implemented in main firmware, so it could be unavailable
if the main firmware is corrupted. Then other method of update based on internal CPU flashing
routine should be used.
This method requires the calc to be switched in so called 'Bootloader mode'.
Once activated, the internal bootloader exposes standard DFU interface and can be programed
by any DFU programming software with limitation that firmware is plain binary file not file
in general .dfu format, so the programming software has to support it. Following chapters cover
use of two programs able to use this DFU interface:
 GUI based <<dm_tool_update,dm_tool>> and command line utility <<dfu_util_update,dfu-util>>.


Availability of the particular update method on mainstream operating systems outlines following table:

[options="header",width="60%"]
|=============================================
|             | <<quick_update_guide,FAT disk>>^[1]^ | <<dm_tool_update,dm_tool>>  | <<dfu_util_update,dfu-util>>^[2]^
|Windows      | X           | X       |  X
|Linux i686   | X           | X       |  X
|Linux x86_64 | X           | X       |  X
|macOS        | X           |         |  X
|=============================================

[1] FAT disk update is available since DMCP version 3.5, you have to
 use other firmware update method if calculator contains earlier firmware version

[2] macOS users can get dfu-util via Homebrew




////

   ▄▄▄  █                                ▀                                    ▄▄▄▄      ▄▄▄▄▄▄
 ▄▀   ▀ █ ▄▄    ▄▄▄▄   ▄▄▄       ▄▄▄   ▄▄▄    ▄ ▄▄    ▄▄▄    ▄▄▄      ▄   ▄  ▀   ▀█         █▀
 █      █▀  █  █▀ ▀█  █   ▀     █   ▀    █    █▀  █  █▀  ▀  █▀  █     ▀▄ ▄▀    ▄▄▄▀        ▄▀
 █      █   █  █   █   ▀▀▀▄      ▀▀▀▄    █    █   █  █      █▀▀▀▀      █▄█       ▀█       ▄▀
  ▀▄▄▄▀ █   █  ▀█▄▀█  ▀▄▄▄▀     ▀▄▄▄▀  ▄▄█▄▄  █   █  ▀█▄▄▀  ▀█▄▄▀       █    ▀▄▄▄█▀  █   ▄▀
                ▄  █
                 ▀▀
////

ifeval::["{platform}" == "DM42"]

[[changes_since_3.7]]
=== Changes since v3.7

Since version 3.7 the firmware for the calculator contains only operating system (called DMCP).
{platform} program could be loaded separately as described in section <<prog_update,"Program update">>.

Instructions for quick update of both DMCP firmware and program load are in
<<quick_update_guide,"Quick Update Guide">>.

There is new DMCP User Manual future plan which should contain information about SDK and program
development for DMCP platform. Before the manual becomes available here are some useful links
related to DMCP development:

- Source code for {pgmname} program: https://github.com/swissmicros/{pgmname} +
  Follow instructions in README files for program building

- Source code for base DMCP_SDK with simple "Hello World" program: https://github.com/swissmicros/DMCP_SDK +
  Follow instructions in README files for program building

- More enhanced SDK demo: https://github.com/swissmicros/SDKdemo. +
  It is simple RPN style calculator with
+
--
 .. Power management
 .. LCD printing
 .. Keyboard handling
 .. Use of Intel® Decimal Floating-Point Math Library (which leads to project with data in QSPI flash)
 .. Menu system
--
+
And as usually, follow instructions in README files for program building.

IMPORTANT: Developing programs for embedded systems requires some level of expertise and SwissMicros doesn't
have enough resources to make individual support for program building and SDK use.

endif::[]







////
  ▄▄▄▄           ▀          █         ▄    ▄            █          ▄                ▄▄▄           ▀       █
 ▄▀  ▀▄ ▄   ▄  ▄▄▄    ▄▄▄   █   ▄     █    █ ▄▄▄▄    ▄▄▄█   ▄▄▄  ▄▄█▄▄   ▄▄▄      ▄▀   ▀ ▄   ▄  ▄▄▄    ▄▄▄█   ▄▄▄
 █    █ █   █    █   █▀  ▀  █ ▄▀      █    █ █▀ ▀█  █▀ ▀█  ▀   █   █    █▀  █     █   ▄▄ █   █    █   █▀ ▀█  █▀  █
 █    █ █   █    █   █      █▀█       █    █ █   █  █   █  ▄▀▀▀█   █    █▀▀▀▀     █    █ █   █    █   █   █  █▀▀▀▀
  █▄▄█▀ ▀▄▄▀█  ▄▄█▄▄ ▀█▄▄▀  █  ▀▄     ▀▄▄▄▄▀ ██▄█▀  ▀█▄██  ▀▄▄▀█   ▀▄▄  ▀█▄▄▀      ▀▄▄▄▀ ▀▄▄▀█  ▄▄█▄▄ ▀█▄██  ▀█▄▄▀
     █                                       █
                                             ▀
////

[[quick_update_guide]]
=== Quick Update Guide (FAT disk update)

ifeval::["{platform}" == "DM42"]
Here we will update DMCP system and {platform} program at once using combined flashing file.

:fwfile: DMCP_flash_3.10_DM42-3.10.bin
:fwtmpl: DMCP_flash_x.x_DM42-y.y.bin
endif::[]

ifeval::["{platform}" == "DM41X"]
This chapter describes update of complete {platform} firmware (i.e. DMCP system, DM41X program and flash area)
at once using combined firmware file.

:fwfile: DMCP_flash_3.16_DM41X-1.10.bin
:fwtmpl: DMCP_flash_x.x_DM41X-y.y.bin
endif::[]


Prerequisites::
`{fwtmpl}` - Complete {platform} firmware file e.g. `{fwfile}` +


*Steps*

. Activate USB disk from `SETUP -> File -> Activate USB Disk`
  or alternatively from <<dmcp_sys_menu,DMCP System menu>>.
. Connect USB cable from {platform} to PC/Mac computer.
. Copy the `{fwtmpl}` file from the PC/Mac computer to root folder of calculator disk.
. Eject (safely remove) the calculator disk from PC/Mac computer. *Please, be patient this can
  take some time. Don't unplug USB cable until safely ejected from OS.*
. Calculator detects presence of new firmware file and asks for update. You can confirm it immediately or press btn:[EXIT]
  key and activate flashing process later using `Flash firmware from FAT` either from {platform} program `SETUP -> System` or
  directly from <<dmcp_sys_menu,DMCP System menu>> `Enter System Menu`
. Once finished the calculator resets and should restart to updated {platform}.






ifeval::["{platform}" == "DM42"]

[[dmcp_pgm_update_quide]]
=== DMCP and PGM Update Guide

NOTE: Since version 3.7

Here we will update DMCP system and {platform} program separately, therefore we need two files for that:

Prerequisites::
`DMCP_flash_x.x.bin` - DMCP system file, e.g. `DMCP_flash_3.10.bin` +
`{platform}-x.x.pgm` - {platform} program file, e.g. `{platform}-3.10.pgm`


*Steps*

. Activate USB disk from {platform} program `SETUP -> File -> Activate USB Disk`
  or directly from <<dmcp_sys_menu,DMCP System menu>>.
. Connect USB cable from {platform} to PC/Mac computer.
. Copy both `DMCP_flash_x.x.bin` and `{platform}-x.x.pgm` files from the PC/Mac computer to root folder of calculator disk.
. Eject (safely remove) the calculator disk from PC/Mac computer. *Please, be patient this can
  take some time. Don't unplug USB cable until safely ejected from OS.*
. Calculator detects presence of new firmware file and asks for update. You can confirm it immediately or press kbd:[EXIT]
  key and activate flashing process later using "Flash firmware from FAT" either from {platform} program `SETUP -> System` or
  directly from <<dmcp_sys_menu,DMCP System menu>> `Enter System Menu`
. Once finished the calculator resets and displays the <<dmcp_sys_menu,DMCP System menu>>.
. Choose "Load Program" and select appropriate `{platform}-x.x.pgm` file, loading process should start
. Once loaded the system should (after key press) restart to {platform} program.





////
 ▄▄▄▄▄                                                   ▀▀█                      █       ▄                   █
 █   ▀█  ▄ ▄▄   ▄▄▄    ▄▄▄▄   ▄ ▄▄   ▄▄▄   ▄▄▄▄▄           █     ▄▄▄    ▄▄▄    ▄▄▄█      █  ▄   ▄  ▄▄▄▄    ▄▄▄█
 █▄▄▄█▀  █▀  ▀ █▀ ▀█  █▀ ▀█   █▀  ▀ ▀   █  █ █ █           █    █▀ ▀█  ▀   █  █▀ ▀█     █   █   █  █▀ ▀█  █▀ ▀█
 █       █     █   █  █   █   █     ▄▀▀▀█  █ █ █           █    █   █  ▄▀▀▀█  █   █    █    █   █  █   █  █   █
 █       █     ▀█▄█▀  ▀█▄▀█   █     ▀▄▄▀█  █ █ █           ▀▄▄  ▀█▄█▀  ▀▄▄▀█  ▀█▄██   █     ▀▄▄▀█  ██▄█▀  ▀█▄██
                       ▄  █                                                          ▀             █
                        ▀▀                                                                         ▀
////

[[prog_update]]
===  Program Loading/Update

NOTE: Since version 3.7

Use this if you want to switch between programs or load new program to already loaded DMCP system.

DMCP system can have one loaded program and only loaded program can be started.
Programs have `.pgm` extension and are expected to be stored in root folder of calculator disk.

Prerequisites::
Program file with `.pgm` extension, e.g. `DM42-3.10.pgm`, `SDKdemo-1.0.pgm`, etc.


*Steps*

. Activate USB disk from {platform} program `SETUP -> File -> Activate USB Disk`
  or directly from <<dmcp_sys_menu,DMCP System menu>>.
. Connect USB cable from {platform} to PC/Mac computer.
. Copy the program file to root folder of calculator disk.
. Eject (safely remove) the calculator disk from PC/Mac computer. *Please, be patient this can
  take some time. Don't unplug USB cable until safely ejected from OS.*
. Issue "Load Program" from <<dmcp_sys_menu,DMCP System menu>>. This menu can be reached from {platform} program
  at `SETUP -> System -> Enter System Menu->Reset to DMCP menu`.
. Program list from root folder of FAT disk is displayed. Choose required program, press kbd:[ENTER].
  After confirmation question the loading process should start.
. Once loaded the system should (after key press) restart to loaded program.

If anything goes wrong, like the current DMCP system is older than program requires,
the restart ends in Program Info screen which should show reason why program
cannot start.




[[DMCP_update_guide]]
=== DMCP Update Guide

Here we will update DMCP system only. Note that this will end just in <<dmcp_sys_menu,DMCP menu>> and you will need
to <<prog_update,load some program>> to get some _real_ functionality.

Prerequisites::
`DMCP_flash_x.x.bin` - DMCP system file, e.g. `DMCP_flash_3.10.bin` +

*Steps*

. Activate USB disk from {platform} program `SETUP -> File -> Activate USB Disk`
  or directly from <<dmcp_sys_menu,DMCP System menu>>.
. Connect USB cable from {platform} to PC/Mac computer.
. Copy the `DMCP_flash_x.x.bin` file from the PC/Mac computer to root folder of calculator disk.
. Eject (safely remove) the calculator disk from PC/Mac computer. *Please, be patient this can
  take some time. Don't unplug USB cable until safely ejected from OS.*
. Calculator detects presence of new firmware file and asks for update. You can confirm it immediately or press kbd:[EXIT]
  key and activate flashing process later using `Flash firmware from FAT` either from {platform} program `SETUP -> System` or
  directly from <<dmcp_sys_menu,DMCP System menu>> `Enter System Menu`
. Once finished the calculator resets and should restart to <<dmcp_sys_menu,DMCP menu>>.


endif::[]












[[bootloader_mode_activation]]
=== Bootloader mode activation

Bootloader mode can be activated from main Setup menu: `SETUP -> System -> Bootloader`
or by using RESET and PGM button.

The sequence of entering bootloader mode using RESET and PGM button is:

- Press and hold PGM button
- Press and release the RESET button
- Release the PGM button

Older models have both buttons accessible through the holes in the calculator backplate.
Newer models have one hole in the backplate for RESET button only, therefore the backplate should
be removed first, then use the RESET and PGM buttons directly on PCB.





////

     █               ▄                  ▀▀█
  ▄▄▄█  ▄▄▄▄▄      ▄▄█▄▄   ▄▄▄    ▄▄▄     █
 █▀ ▀█  █ █ █        █    █▀ ▀█  █▀ ▀█    █
 █   █  █ █ █        █    █   █  █   █    █
 ▀█▄██  █ █ █        ▀▄▄  ▀█▄█▀  ▀█▄█▀    ▀▄▄
              ▀▀▀▀▀▀
////

[[dm_tool_update]]
=== FW Update Using dm_tool

TIP: The latest version of `dm_tool` can be downloaded from
 the https://technical.swissmicros.com/tools/[Tools web page].


==== Prerequisites for Windows

You have to install libusb driver as described here: http://technical.swissmicros.com/doc/libusb_install/libusb_install.html.


==== Prerequisites for Linux

[[_usb_device_access_rights]]
===== USB device access rights

This configuration is optional.

You can allow access to the DFU device for users in `plugdev` group by running as root:

----
cd /etc/udev/rules.d/
cat << OI > 49-stm32-dfuse.rules
# This is udev rules file (place in /etc/udev/rules.d)
# Makes STM32 DfuSe device accessible to the "plugdev" group

ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="664", GROUP="plugdev"
OI
udevadm control --reload-rules
----

Then add users to `plugdev` group.



[[launching_dm_tool]]
==== Launching dm_tool


Switch the calculator to bootloader mode:::
  From menu or by RESET+PGM buttons (see <<bootloader_mode_activation, Bootloader mode activation>>).

Connect the calculator to the PC:::
  Be sure the libusb driver is installed if used in Windows (http://technical.swissmicros.com/doc/libusb_install/libusb_install.html).

Launch `dm_tool`:::
  It can be launched by clicking on the exe file or from command line with firmware filename as argument.

If everything works well and the calculator was connected before launching `dm_tool`,
then the message on the right side of [Program] button should show device number.
If it shows "No DFU capable devices found (Click to refresh)" try to click at the message
and it should display the ID of connected device after refresh and
----
Memory layout:
    0x8000000-0x80fffff:  size 1024kB = 512*2kB pages
----
in the text area.

If the message "No DFU capable devices found" still remains there something is wrong with libusb driver installation or connection to the calculator or the calculator isn't in bootloader mode.


Finally press the `[Program]` button to flash new firmware.






////

     █    ▄▀▀                         ▄      ▀    ▀▀█
  ▄▄▄█  ▄▄█▄▄  ▄   ▄         ▄   ▄  ▄▄█▄▄  ▄▄▄      █
 █▀ ▀█    █    █   █         █   █    █      █      █
 █   █    █    █   █   ▀▀▀   █   █    █      █      █
 ▀█▄██    █    ▀▄▄▀█         ▀▄▄▀█    ▀▄▄  ▄▄█▄▄    ▀▄▄

////

[[dfu_util_update]]
=== FW Update Using dfu-util

TIP: macOS users can get dfu-util via Homebrew

TIP: Linux users (and possibly macOS users too) can avoid `sudo` use by setting appropriate user rights
 for DFU interface, see <<_usb_device_access_rights,user rights configuration for Linux>>.

Note that `dfu-util` is command line utility and you have to be able to launch terminal application and
launch commands from console. If you are new to this, here are some tutorials:

- macOS: https://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line
- Linux: https://www.digitalocean.com/community/tutorials/an-introduction-to-the-linux-terminal
- Windows: https://www.bleepingcomputer.com/tutorials/windows-command-prompt-introduction/

Now you can proceed with the following steps:


Switch the calculator to bootloader mode:::
  From menu or by RESET+PGM buttons (see <<bootloader_mode_activation, Bootloader mode activation>>).

Connect the calculator to the PC:::
  You can list information about connected DFU device using console command `sudo dfu-util -l`
+
Sample output of this command (from macOS)
+
----
$ sudo dfu-util -l
Password:
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Found Runtime: [05ac:828b] ver=0149, devnum=6, cfg=1, intf=3, path="29-1.8.1.3", alt=0, name="UNKNOWN", serial="UNKNOWN"
Found DFU: [0483:df11] ver=2200, devnum=14, cfg=1, intf=0, path="20-4", alt=2, name="@OTP Memory /0x1FFF7000/01*0001Ke", serial="207B35994E34"
Found DFU: [0483:df11] ver=2200, devnum=14, cfg=1, intf=0, path="20-4", alt=1, name="@Option Bytes  /0x1FFF7800/01*040 e/0x1FFFF800/01*040 e", serial="207B35994E34"
Found DFU: [0483:df11] ver=2200, devnum=14, cfg=1, intf=0, path="20-4", alt=0, name="@Internal Flash  /0x08000000/512*0002Kg", serial="207B35994E34"
----
+
Where lines `Found DFU: [0483:df11]` indicate that calculator is correctly connected to PC and switched into bootloader mode.

Prepare firmware file:::
  Download the latest firmware file from https://technical.swissmicros.com/{webdir}/firmware/ and ensure
  it is accessible from current directory in console e.g. by `ls -l {fwfile}`.
+
Or you can alternatively download firmware file directly to current directory using command
(edit to use correct firmware file name according to before-mentioned page)
+
[source, subs="attributes"]
----
curl -O https://technical.swissmicros.com/{webdir}/firmware/{fwfile}
----



Launch dfu-util command:::
   You can start flashing using command (edit to use correct firmware file name)
+
[source, subs="attributes"]
----
sudo dfu-util -D {fwfile} -d 0483:df11 -a "@Internal Flash  /0x08000000/512*0002Kg" -s 0x8000000
----
+
Please, be patient, it takes some time (few minutes).
+
Press RESET button after `dfu-util` finishes the flashing.



Example output of `dfu-util`
[source, subs="attributes"]
----
$ dfu-util -D {fwfile} -d 0483:df11 -a "@Internal Flash  /0x08000000/512*0002Kg" -s 0x8000000
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting # 0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 756288
Download	[=========================] 100%       756288 bytes
Download done.
File downloaded successfully

real	1m55.929s
user	0m0.044s
sys	0m0.048s
----




