:allow-uri-read:
:stylesheet: https://tech.swissmicros.com/User-Manuals/usermanuals.css
:linkcss:
:toc: left
:toclevels: 5
:lang: en

:version: 1.0

:title-page: DM41X Quick Reference
= DM41X Quick Reference
SwissMicros GmbH
Copyright 2019-{localyear} v{version} {docdate}

== DM41X Quick Reference

[[Home]]
=== Contents

* link:#about[About this manual]
* link:#helpnav[I. Help Navigation]
* link:#dm41x_ref[II. DM41X Unique Features]
* link:#41c_ref[III. Key 41C Reference Topics]
* link:#ext_ref[IV. External References]

 +

[[about]]
=== About this manual

This manual is an excerpt of the more detailed DM41X User Manual
available at +
https://technical.swissmicros.com/dm41x/doc +
 +

[[helpnav]]
=== I. Help Navigation

==== Global navigation

Use [.button]#A# or [.button]#ON# to exit +
Use [.button]#B# to jump to link:#Home[Contents] +
Use [.button]#C# to open help file from disk +

==== Navigation keys

Press [.button]#+# to move one line forward +
Press [.button]#-# to move one line backward +
Press [.button]#×# to move one page forward +
Press [.button]#÷# to move one page backward +
Use arrow keys to navigate to next/previous link +
[.button]#ENTER# to follow link +
[.button]#←# to go back to place where was [.button]#ENTER# used. +
The arrow keys navigate to the next/previous page if there is no link to
navigate to.

==== Numpad-like navigation keys

[.button]#2#/[.button]#8# - single line down/up +
[.button]#3#/[.button]#9# - page down/up +
[.button]#4#/[.button]#6# - prev/next link (same as arrows) +
[.button]#5# - follow the link (same as [.button]#ENTER#) +
[.button]#7# - jump to the link:#Home[Contents](same as [.button]#B#) +
 +

[[dm41x_ref]]
=== II. DM41X Unique Features

* link:#lcd_viewa[A. LCD Views and DSP Control]
* link:#cstm[B. CST Menu use and Setup]
* link:#help_access[C. Help Access]
* link:#rom_map[D. ROM MAP]
* link:#state_files[E. Load/Save State]
* link:#raw_files[F. Load/Save RAW files]
* link:#usb_disk[G. USB Disk mode access]
* link:#flags[H. Flags]
* link:#scrshots[I. Screen shots]
* link:#off_images[J. OFF Screen Images]
* link:#new_fns[K. New Built-in Functions]
* link:#modules[L. Modules]
* link:#menus[M. Menu summary]

 +

[[lcd_viewa]]
=== A. LCD Views and DSP Control

The large screen allows the display of full calculator stack at once.
Which is the default view. +
There are other possible views both in calculation mode and programing
mode. +
View modes are cycled using [.button]#DSP# key. +
Calculation mode:

* Stack view
* link:#si_view[SI view] XA
* link:#si_view[SI view] XY

Programming mode:

* link:#si_view[SI pgm view] - single line basic view
* Multiline pgm view - 4 lines
* Multiline pgm view - 6 lines
* Multiline pgm view - 8 lines

 +

[[si_view]]
==== SI View

Enhanced "System Info" view:

* link:#si_line1[SI first line] - Status of Alarms
* link:#si_line2[SI second line] - Memory status
* link:#si_line3[SI third line] - Program and printer status

[[si_line1]]
==== SI first line

Displays status of your Alarms, there are 3 icons on the far left:

* A coffee cup indicates that no alarms are pending
* An alarm clock indicates at least one pending alarm
* A bell indicates a past-due alarm

Next, the alarm text of your next pending (or past-due) alarm is
shown. +
On the far right, the number of pending alarms is shown in
parentheses. +

[[si_line2]]
==== SI second line

Displays the memory status. +
On the far left, free (available for use) main Program Memory and free
Extended Memory are shown as xxx/yyy. +
On the far right on line 2 is the current 41 SIZE status, indicating how
many data storage registers have been allocated. +

[[si_line3]]
==== SI third line

Displays information about your current Program and Printer status. +
Starting from the left, the program’s name (topmost global Alpha label),
current line number and max number of lines is displayed. +
On the far right of line-3, the current printer status is displayed
following the PRN: label as follows:

* MAN - Manual Print Mode
* TRA - Trace Print Mode
* NRM - Normal Print Mode
* OFF - The Printer has been disabled
* N/A - The Printer Module has not been plugged-in

 +

[[cstm]]
=== B. CST Menu use and Setup

CST functionality allows to assign commands to keys in the similar way
as the standard ASN function works. Those assignments are then
accessible in CST screen invoked by pressing [.button]#CST# key. +
CST configuration could be activated by the [.button]#SHIFT#
[.button]#CST# key sequence, it is possible to make 16 assignments to
keys from 'A' to 'P' and assign commands to three special keys:
[.button]#SHIFT# [.button]#▲#, [.button]#SHIFT# [.button]#▼# and
[.button]#SHIFT# [.button]#ALPHA#. The key assignments could be also
save/loaded to/from the .cst files in CST configuration screen. +
The default directory for the .cst files is /KEYS/. +
 +

[[help_access]]
=== C. Help Access

DM41X contains internal help browser. +
This functionality is accessible by pressing [.button]#CST#
[.button]#1#. +
The default directory for the .html help files is /HELP/. +
Calculator comes with basic set of help files, but it allows to add
other user files. +
Note that the html browser implementation is extremely minimalistic and
help files have to be designed to comply with all the limitations. +
Basic information for creation of user link:help_devel.html[help
files]. +
 +

[[rom_map]]
=== D. ROM Map

ROM Map shows ROM placement in pages and banks. +
This functionality is accessible by pressing [.button]#CST#
[.button]#2# +
Each row corresponds to page denoted at the beginning of the line,
columns represent banks. +
RAM pages are shown in first bank if other only as RAM banking isn’t
supported now. +
Soft menu items allow to:

* [.button]#Pg 8-F#/[.button]#Pg 0-7# - Toggle page range
* [.button]#ROM-id#/[.button]#ROM-nr# - Toggle ROM labels
* link:#am_menu[[.button]#⇒ AM#] - Invokes Active Modules screen.
* [.button]#ModLst# - Switches right side between 'Modules list' and
'Modules by page'

 +

[[state_files]]
=== E. Load/Save State

It is possible to load and save calculator state - i.e. contents of
memory and CPU registers from/to .d41 file from/to link:#usb_disk[FAT
disk] (respectively). +
Note that this loads only calculator memory and doesn’t affect state of
currently loaded modules. +
The default directory for the .d41 files is /STATE/. +
This functionality is accessible in link:#file_menu[File menu]. +
 +

[[raw_files]]
=== F. Load/Save RAW files

It is possible to load and save programs from/to standard .raw files
from/to link:#usb_disk[FAT disk] (respectively). +
Using the functional equivalent of GETP/SAVEP extended memory command.
Only that the .raw file is read/written from/to FAT disk instead of
extended memory. +
Note that the program name for save has to be prepared in ALPHA
register. +
Default directory for .raw files is /PROG/. +
This functionality is accessible through link:#cstm[CST menu] or in
link:#file_menu[File menu]. +
 +

[[usb_disk]]
=== G. USB Disk mode access

The calculator has 6MB of internal flash storage formatted as a FAT
filesystem that is used for loading/saving programs and for backing up
calculator state. +
It is accessible as USB disk when activated via the menu File >
link:#usb_disk_menu[Activate USB Disk]. +
There are several directories with special names (and purpose) on the
FAT disk: +

* /HELP - Contains help file(s) for built-in DM41X help that
link:#help_access[can be activated] from CST menu.
* /KEYS - Contains files with link:#cstm[Custom Menu] key mappings.
* /MODS - Default directory for module files.
* /OFFIMG - link:#off_images[Bitmap files] from this directory are
displayed when the calculator is turned off
* /PROG - link:#raw_files[Raw files] with programs are loaded/saved
from/to this directory
* /RAM - Contains saved link:#mod_ram[RAM pages]
* /SCREENS - link:#scrshots[Screenshots] of calculator LCD are saved
into this directory
* /STATE - link:#state_files[Calculator state] files with extension .d41
are stored in this directory

 +

[[flags]]
=== H. Flags

Calculator flags could be quickly examined at once on Flag Status screen
accessible by [.button]#CST# [.button]#6#. +
DM41X extends use of some flags:

* Flags 15/16 Control the Printer mode (MAN/TRACE/NORM) as follows:
+
[cols=",,",]
|===
|15 |16 |
|0 - |0 |MAN (manual)
|0 - |1 |NORM (normal)
|1 - |0 |TRACE
|===
* Flag 21 - controls if the printer is enabled or disabled (exactly like
a 41C) and initially follows the state of flag 55 at power-on
* Flag 55 - Indicates printer module presence

 +

[[scrshots]]
=== I. Screen shots

Hold [.button]#SHIFT# and press [.button]#DSP# to get a screenshot. +
You will find a `.bmp` file named according to the current time and date
in the `/SCREENS` folder of the FAT disk. +
 +

[[off_images]]
=== J. OFF Screen Images

The LCD display used in DM41X calculator behaves in the similar way as
e-ink displays and contents of the LCD is visible for a long time after
the calculator is turned OFF. +
This feature is used to display images when the calculator is turned
OFF. +
Custom OFF images could be stored in /OFFIMG/ directory. +
OFF images require specific image format. It has to be .bmp file with
dimensions 400 x 240 and 1 bit depth. +
 +

[[new_fns]]
=== K. New Built-in Functions

* link:#fn_syscm[System Control and Misc]
* link:#fn_alfn[Alpha Functions]
* link:#fn_exmf[Extended Memory Functions:]

[[fn_syscm]]
==== System Control and Misc

* [#fn_slow]#link:#fn_slow[SLOW] - Sets SLOW mode for compatibility with
legacy Modules#
* [#fn_fast]#link:#fn_fast[FAST] - Restores FAST mode#
* [#fn_fill]#link:#fn_fill[FILL] - Fills the stack with the value in X#
* [#fn_x_i_y]#link:#fn_x_i_y[X<I>Y] - Exchanges the contents of IND X
and IND Y#
* [#fn_trng]#link:#fn_trng[TRNG] - Time-Based (True) Random Number
Generator#
* [#fn_lkaoff]#link:#fn_lkaoff[LKAOFF] - Turns Local KA (Key
Assignments) off, i.e. those assigned to the two top rows#
* [#fn_lkaon]#link:#fn_lkaon[LKAON] - Turns Local KA (Key Assignments)
back on#

 +

[[fn_alfn]]
==== Alpha Functions

* [#fn_absp]#link:#fn_absp[ABSP] - ALPHA Back Space. Deletes the
rightmost char in ALPHA#
* [#fn_aint]#link:#fn_aint[AINT] - Appends integer value from Reg X to
ALPHA (includes sign)#
* [#fn_aswap]#link:#fn_aswap[ASWAP] - Swaps ALPHA strings around the
comma characters, i.e. A,B changes to B,A#
* [#fn_clac]#link:#fn_clac[CLAC] - Clears ALPHA after the comma
character, i.e. A,B changes to A,#

 +

[[fn_exmf]]
==== Extended Memory Functions:

* [#fn_clem]#link:#fn_clem[CLEM] - Clears all Extended Memory#
* [#fn_eds]#link:#fn_eds[ED$] - Enhanced ASCII File Editor with support
for lower-case and special characters. The operation is controlled by
the status of the [.button]#ALPHA# annunciator. [.button]#ALPHA# On is
the standard mode, selected when you first enter the editor. Switch
[.button]#ALPHA# OFF to access non-keyable characters in the standard
mode. Use the shifted keys to access the lower-case characters and the
un-shifted keys to access the special characters.#
* [#fn_flcopy]#link:#fn_flcopy[FLCOPY] - Copies the content of a file
into another. Both files must exist and be of the same type. The
destination file should be of equal size or larger than the source
file.#
* [#fn_flhd]#link:#fn_flhd[FLHD] - Returns to X the address (in decimal)
of the File Header. Stack lifts if CPU F11 is set#
* [#fn_fltype]#link:#fn_fltype[FLTYPE] - Returns to X the type of the
file, ie. 1 for program, 2 for Data, etc. Stack lifts if CPU F11 is set#
* [#fn_renmfl]#link:#fn_renmfl[RENMFL] - Renames an X-Mem file. Alpha
contains OLDNAME,NEWNAME#
* [#fn_retpfl]#link:#fn_retpfl[RETPFL] - Re-types an X-Mem file. X has
the new type value (1 to 15)#
* [#fn_workfl]#link:#fn_workfl[WORKFL] - Appends the name of the current
("Working") X-Mem file to [.button]#ALPHA#.#

 +

[[modules]]
=== L. Modules

* link:#mod_format[Supported format]
* link:#mod_use[How to add and use modules]
* link:#mod_print[Printer module]
* link:#mod_flash[Import modules to Flash]
* link:#mod_am[Activating modules from Flash]
* link:#mod_order[Module load order]
* link:#mod_ram[Module RAM]

 +

[[mod_format]]
=== Supported format

DM41X is able to load and use usual .mod files only. +
 +

[[mod_use]]
=== How to add and use modules

* Load .mod file to DM41X - using link:#usb_disk[USB disk] functionality
* Import .mod file to internal Flash Module area - see how to
link:#mod_flash[Import modules to Flash]
* Add module to the 'Active Modules' list - see how to
link:#mod_am[Activate modules]

 +

[[mod_flash]]
=== Import modules to Flash

_Flash Module Area_ is special region of flash memory dedicated for
module use. It is the only place from where the emulator can access
module ROMs and run module code. +
Thus, all modules before link:#mod_am[activation] have to be loaded to
_Flash Module Area_. +
Use [.button]#Imprt# in link:#mmf_menu[Manage Modules in flash] for
that. +
 +

[[mod_am]]
=== Activating modules from Flash

'Activating module' corresponds to module plug-in on real calculator. +
Module has to be first link:#mod_flash[loaded in Flash Module Area]. +
Use [.button]#Plug# in link:#am_menu[Active Modules] for module
plug-in. +
 +

[[mod_print]]
=== Printer module

There is preloaded 'PRINTER' module to simplify printer use. +
link:#mod_am[Activate] PRINTER module to enable printer functionality. +
 +

[[mod_order]]
=== Module load order

Module order in link:#mod_am[Active modules list] is relevant. Pages
assigned to modules are based on this order and information in original
.mod files. +
This list describes procedure for page assignment:

* Pass 0 - ROMs assigned in .mod files to fixed pages go exactly there.
* Pass 1 - Others ROMs are assigned to pages 8-F in order of appearance
- first those with prescribed mutual relative positions (in single .mod
file).
* Pass 2 - Finally ROMs using single pages with no other requirements
are placed at free pages.

 +

[[mod_ram]]
=== Module RAM

The DM41X can provide up to 8 Pages of RAM. +
Thus, any module can define its own RAM (in .mod file) and subsequently
access it using WROM(WMLDL) and CXISA(FETCH S&X). HEPAX instructions
WPTOG and BLKMOV are implemented too. +
The only restriction in current implementation is that RAM doesn’t
support banks. +
Contents of RAM pages could be link:#ram_save_menu[saved] and
link:#ram_load_menu[restored] to/from disk. +
 +

[[menus]]
=== M. Menu summary

Main Setup Menu +

* link:#file_menu[1. File menu]
* link:#module_menu[2. Module menu]
* link:#settings_menu[3. Settings menu]
* link:#system_menu[4. System menu]
* 5. About - Displays About screen

 +

[[file_menu]]
=== File menu

* 1. Load DM41 State File > +
Loads the .d41 state files
* 2. Save DM41 State File > +
Saves calculator’s state to a .d41 state file
* 3. Load RAW Program > +
Loads the .raw program file
* 4. Save RAW Program > +
Saves program to .raw file
* [#usb_disk_menu]#5. Activate USB Disk +
Used to copy files from/to a host computer#
* 6. Show Disk Info +
Displays disk status and disk block info

 +

[[module_menu]]
=== Module menu

* [#am_menu]#1. Active Modules (AM) +
Screen for management of active modules#
* [#mmf_menu]#2. Manage Modules in Flash +
Allows to add/remove modules to/from this area and display information
about modules#
* 3. Module ROM Map +
ROM map shows ROM placement in pages and banks
* link:#loadmod_menu[4. Load Modules]
* link:#savemod_menu[5. Save Modules]
* [#ram_load_menu]#6. Load RAM Pages > +
Fills RAM Area from the file#
* [#ram_save_menu]#7. Save RAM Pages > +
Saves RAM Area into the file.#

 +

[[loadmod_menu]]
=== Load Modules

* 1. Load AM List +
Loads Active Modules from the .m41 file
* 2. Load Flash and AM Lists +
Loads both AM list and .mod files into the Flash according to the .m41
file list
* 3. Load Flash, clear AM List +
Loads only .mod files into the Flash according to the .m41 file list

 +

[[savemod_menu]]
=== Save Modules

* 1. Save AM List only +
Saves Active Modules list into the .m41 file
* 2. Save Flash and AM Lists +
Saves both Active Modules list and list of .mod files loaded into Flash
to the .m41 file

 +

[[settings_menu]]
=== Settings menu

* 1. Set Time > +
Sets time and time format
* 2. Set Date > +
Sets date and date format
* 3. Slow Auto-repeat +
Allows to lower key repeat rate
* 4. Printer Line Delay +
Sets IR printer line delay
* 5. Create Full Backup +
Complete calculator's backup
* 6. Restore from Backup +
Restore from complete backup
* 7. Export Settings to 'param.cfg' +
Writes Persistent Configuration Settings to the /param.cfg file
* 8. Reset settings to defaults +
Resets Persistent Configuration Settings to defaults.

 +

[[system_menu]]
=== System menu

* 1. Flash firmware from FAT +
Starts flashing the firmware file from root directory of FAT disk
* 2. Bootloader +
Activates bootloader mode for firmware flashing
* 3. Program Info +
Displays information about currently loaded DM41X
* 4. Reset to DMCP menu +
Reboots calculator to DMCP system menu
* 5. Format FAT Disk > +
Format the internal FAT disk storage
* 6. FAT Disk Media Test > +
Checks whole flash disk FAT area for bad blocks (disk is erased)
* 7. Power OFF mode +
Don't touch this, only for OFF current diagnosing
* 8. Self Test +
Opens self test menu

 +

[[41c_ref]]
=== III. Key 41C Reference Topics

* link:#41c_isg_dse[A. ISG/DSE Format]
* link:#41c_date[B. Date Formats]
* link:#41c_time[C. Time Formats]
* link:#41c_alarm[D. Alarm formats]

 +

[[41c_isg_dse]]
=== A. ISG/DSE Format

The functions ISG (increment and skip if greater) and DSE (decrement and
skip if equal) are used to effectively control the loops using the
number +
iiiii.fffcc where:

* iiiii is the current counter value
* fff is the counter test value
* cc is the increment value, if the cc value isn't specified, it is
taken as cc=01

Each time ISG is executed, it first increments iiiii by cc, then it
tests to see if iiiii is greater than fff. If it is then the next
program line is skipped. +
Each time DSE is executed, it first decrements iiiii by cc, then it
tests to see if iiiii is equal to or less than fff. If it is then the
next program line is skipped. +
 +

[[41c_date]]
=== B. Date Formats

For date inputs:

* Use the (MM.DDYYYY) format by default or after MDY function
* Use the (DD.MMYYYY) format after DMY function

DATE function places date into the X-register in currently selected
DMY/MDY format. +
 +

[[41c_time]]
=== C. Time Formats

Use the (HH.MMSShh) format for time inputs. +
Time inputs for hours later than 12:00 p.m. (noon) can be input either
as negative numbers or in the 24-hours time format. +
TIME function places time into the X-register (always) in 24-hours time
format. +
 +

[[41c_alarm]]
=== D. Alarm formats

All clock alarms are set by XYZALM (XYZ alarm) function using the data
in the X, Y, Z, and ALPHA registers:

* link:#alm_rep[Z - Alarm Repeat Interval] +
HHHH.MMSSt
* link:#alm_date[Y - Alarm Date] +
MM.DDYYYY or DD.MMYYYY
* link:#alm_time[X - Alarm Time] +
HH.MMSSt
* link:#alm_alpha[ALPHA - Message or Function] +
Blank, Message, Label or Function

 +

[[alm_rep]]
=== Z - Alarm Repeat Interval

This parameter (r) causes the alarm to repeat itself after the specified
interval. +
Format of r: HHHH.MMSSt +
Range of r: 10 Seconds ≤ r < 10,000 Hours +
No Repeat: Use r = 0 +
 +

[[alm_date]]
=== Y - Alarm Date

This parameter (d) is the date on which you want the alarm to
activate. +
Format of d: MM.DDYYYY or DD.MMYYYY +
Range of d: January 1, 1900 through December 31, 2199 +
Current date: Use d = 0 +
 +

[[alm_time]]
=== X - Alarm Time

This parameter (T) is the time of day at which you want the alarm to be
activated. +
Format of T: HH.MMSSt +
Range of T: –23.59599 ≤ T ≤ 23.59599 +
 +

[[alm_alpha]]
=== ALPHA - Message or Function

Contents of ALPHA register determines the alarm type:

* Tone Alarm - [Empty] +
Alarm produces a series of tones and a flashing time/date display.
* Message Alarm - [Alpha string Message] Up to 24 Characters +
Alarm produces a flashing ALPHA string message and a series of tones.
* Interrupting Control Alarm - [↑↑program label] or [↑↑function name] +
Executes a program or a plug-in-device function that you specify.
* Noninterrupting Control Alarm - [↑program label] or [↑function name] +
Executes a program or a plug-in-device function only while the
calculator is turned off or is displaying the clock.

 +

[[ext_ref]]
=== IV. External References

* link:am_help.html[Angel's Help]

 +
 +
